### ISSUE TITLE
usernames without tags (4-digit numbers) still have #0 at the end

### ISSUE THREAD

**Issue by infopcgood** [v1rbox/discox#172]
**Describe the bug**
when a user who has a username without tags (for example, @infopcgood), their nickname is displayed with an extra #0 at the end. (for example, infopcgood#0)

**To Reproduce**
Look at #starboard in the discord server.

**Expected behavior**
when a user who has a username without tags (for example, @infopcgood), their nicknames should be displayed without the extra #0 in the end. (for example, infopcgood)

**Screenshots**
![image](https://github.com/v1rbox/discox/assets/112328126/6955d37c-2e7d-4be9-89bc-1a541a709029)

**Comment by justinlime** [comment]
Fixed with https://github.com/v1rbox/discox/pull/169
