### ISSUE TITLE
Smartphone OS's

### ISSUE THREAD

**Issue by TollerNamen** [v1rbox/discox#46]
If we have Android whitelisted, can we have other Smartphone OS's whitelisted like /e/OS etc.

**Comment by logicguy1** [comment]
Do you have a list of phone osses you want added? I'm not really in the phone is space rn

**Comment by TollerNamen** [comment]
Sure:

GrapheneOS
KaiOS
Sailfish OS
Plasma Mobile
Ubuntu Touch
Mobian
CalyxOS
LineageOS
HarmonyOS

and my personal favourite:
/e/ OS

**Comment by TollerNamen** [comment]
i would suggest putting them into a 'SmartphoneOSs category' tho

**Comment by logicguy1** [comment]
Maybe rewrite the command to accept role categories, like having them shared in one eg `v!category code add Python`

**Comment by TollerNamen** [comment]
Yes this would make the 'roleadd' function more uniformly. Thats good.
