### ISSUE TITLE
Moving to the AGPL-3.0 License

### ISSUE THREAD

**Issue by Coca162** [v1rbox/discox#57]
While GPL-3.0 requires developers to share modifications of the code if they distribute it, this does not apply to distribution over a network.

To quote [gnu.org](https://www.gnu.org/licenses/why-affero-gpl.en.html):
> The GNU Affero General Public License is a modified version of the ordinary GNU GPL version 3. It has one added requirement: if you run a modified program on a server and let other users communicate with it there, your server must also allow them to download the source code corresponding to the modified version running there.

Since discord bots are only communicating with users over a server you will never have to share any modifications, and so it would be best to use AGPL instead.

**Comment by logicguy1** [comment]
@v1rbox I belive you are the current licence holder

**Comment by v1rbox** [comment]
Done thank you for bringing this up
