### ISSUE TITLE
Calc command doesnt work properly

### ISSUE THREAD

**Issue by AhzDeveloperlol** [v1rbox/discox#61]
**Describe the bug**
Basically the calc command doesnt work as it was suppose to

**To Reproduce**
1. add an alphabet to the command like this: ```2a2```

**Expected behavior**
i expected it to result in an error 

**Screenshots**
![image](https://user-images.githubusercontent.com/70972043/212739705-3f15d878-c00d-487a-93ac-2030aaf037ed.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Pro

**Additional context**
too lazy to find and fix rn and i am also new

**Comment by logicguy1** [comment]
Thank you for the issue, we will look into the problem :)

**Comment by logicguy1** [comment]
@ademyrodev is the author of this command

**Comment by ademyrodev** [comment]
Thank you for reporting this issue. Will try to fix it soon. :+1:

**Comment by ademyrodev** [comment]
Issue was recently fixed.
Turns out I just had to add a check.
Thank you for pointing out this issue!
