### ISSUE TITLE
<*arg> / [*arg] syntax returns empty string when no argument is given

### ISSUE THREAD

**Issue by xsnowstorm** [v1rbox/discox#97]
**Describe the bug**
Commands that use a *arg return an empty string when the argument is not present.

**To Reproduce**
1. Create a command with usage: `[*test]`
2. Print the arguments when the command executes
3. Run the command without any arguments
4. `['']` will be printed to the console

**Expected behavior**
It should be an empty array

**Additional context**
This causes the member type to raise an error (fixed)

**Comment by jtbx** [comment]
Can be closed
